blank_issues_enabled: false
contact_links:
  - name: npm support
    url: https://www.npmjs.com/support
    about: If you need support for problems or to report an incident please contact npm support at support@npmjs.com.
  - name: npm docs
    url: https://docs.npmjs.com/
    about: Need help with using npm? Check out our docs!
  - name: npm CLI RFC
    url: https://github.com/npm/rfcs
    about: Want to propose a change to the CLI? Open an RFC!
  - name: npm status page
    url: https://status.npmjs.org/
    about: Check the status of npm services on our status page.