name: Lock New Issues

on:
  issues:
    types: [opened, transferred]

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Lock new issues when opened
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.lock({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo
            })
